#! TO DO:
#! add a rule for rendering the combined report

#! TO DO:
#! add a rule for building the output of 
#! subproject1/code/01_make_table1.R

#! TO DO:
#! add a rule for building the output of 
#! subproject1/code/02_make_scatter.R

#! TO DO:
#! add a rule for building the output of 
#! subproject2/code/01_models.R
